on: [push]
env:
  NIX_PATH: nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos
  NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}
jobs:
  build:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: nix-build
      - name: Deploy to Edge Storage
        uses: own3d/bunny-action@main
        env:
          BUNNY_API_ACCESS_KEY: ${{ secrets.FTP_PASSWORD }}
          BUNNY_STORAGE_HOSTNAME: uk.storage.bunnycdn.com
          BUNNY_STORAGE_USERNAME: ${{ secrets.FTP_USERNAME }}
          BUNNY_STORAGE_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          BUNNY_PULL_ZONE_ID: 3403550
        with:
          args: deploy --dir=result