on: [push]
env:
  NIX_PATH: nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos
  NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}
jobs:
  build:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: nix-build
      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local_path: './result/*'
          remote_path: '/'
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD }}